
title: My Resume
url: 'http://fatemehzahedi.github.io'
baseurl: '/FatemehZahedi.github.io' #change it according to your repository name



# Profile information
yourname: Fatemeh Zahedi  ## put your name
title: 'PhD Candidate in Mechanical Engineering, Robotic'  ## your title
location: Arizona State University , AZ


## Social Profiles
#facebook: http://www.facebook.com  ## your facebook account url
#twitter: http://www.twitter.com  ## your twitter account url
github: https://github.com/FatemehZahedi  ## your twitter account url
linkedin: https://linkedin.com/in/fatemeh-zahedi-14297081/  ## your linkedin account url
google: https://scholar.google.com/citations?hl=en&user=4S-uN-UAAAAJ  ## your twitter account url
#dribbble: http://www.dribble.com  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
